### ISSUE TITLE
How to check if the request contains the complete body?

### ISSUE THREAD

**Issue by PasinduTennage** [mnlipp/jdrupes-httpcodec#1]
In this library, we can check whether the request has the complete header using,  Decoder.Result.isHeaderCompleted()

Is there a way to check whether the request contains the complete body of the message? 

For example, assume an echo service, where the message to be echoed is 10KB. Then by the time we read the socket for the request, there is a chance that the complete body has not yet received.

**Comment by mnlipp** [comment]
For each received message, there will be an invocation of the decoder that returns a [result](https://static.javadoc.io/org.jdrupes.httpcodec/httpcodec/2.0.1/org/jdrupes/httpcodec/Codec.Result.html) where neither the overflow nor the underflow flag is set. This indicates "message fully received and (last part of) body copied to the receive buffer".

Depending on your buffer sizes and the content of the in-buffer, this may happen after a single invocation of [decode](https://static.javadoc.io/org.jdrupes.httpcodec/httpcodec/2.0.1/org/jdrupes/httpcodec/Decoder.html#decode-java.nio.ByteBuffer-java.nio.Buffer-boolean-) or after several invocations.

Maybe have a look at the [tests](https://github.com/mnlipp/jdrupes-httpcodec/blob/master/test/org/jdrupes/httpcodec/test/http/RequestDecoderTests.java) that feed the complete message or the message split at different boundaries to the decoder.

**Comment by mnlipp** [comment]
Closing this as there was no further feedback.
